# Generated by Django 5.0.3 on 2024-04-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sender', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='user', max_length=8)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('attachments', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=50, unique=True)),
                ('page_id', models.CharField(max_length=50, unique=True)),
                ('access_token', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
