# Generated by Django 5.0.3 on 2024-04-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facebook', '0001_initial'),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='lead_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_sender_chats', to='lead.lead'),
        ),
        migrations.AddField(
            model_name='chat',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_chats', to='facebook.page'),
        ),
        migrations.AddField(
            model_name='chat',
            name='page_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_sender_chats', to='facebook.page'),
        ),
    ]
