# Generated by Django 5.0.3 on 2024-04-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='admin', max_length=8),
        ),
    ]
