# Generated by Django 5.0.3 on 2024-04-10 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_alter_chat_sender'),
        ('lead', '0007_alter_lead_email_alter_lead_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='lead_sender',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='page_sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_chats', to='lead.lead'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(choices=[('page', 'Page'), ('lead', 'Lead')], default='page', max_length=8),
        ),
    ]
