# Generated by Django 5.0.3 on 2024-04-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_sequence_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='delay',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
