version: '3.9'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.local
    ## Library: docker-compose-wait /wait
    ## it can wait for multiple hosts using WAIT_HOSTS: postgres:5432
    command: >
      sh -c "/wait &&
             python manage.py collectstatic --no-input &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             gunicorn tappy.wsgi:application --bind 0.0.0.0:8000"
    volumes:
    - .:/app
    ports:
    - "8000:8000"
    env_file:
      - .env.prod
