version: '3.9'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: >
      sh -c "/wait &&
             python manage.py collectstatic --no-input &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             gunicorn tappy.wsgi:application --bind 0.0.0.0:8000"
    volumes:
    - .:/app
    env_file:
      - .env.prod
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-logs:/var/log/letsencrypt
      - ./static:/app/static
    command: certonly --webroot --webroot-path=/app/static --email jovenntann@gmail.com --agree-tos --no-eff-email --force-renewal -d api.tappy.com.ph
volumes:
  static_volume:
  certs:
  certbot-logs: