# Generated by Django 5.0.3 on 2024-04-07 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_initial'),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('messenger', 'Messenger'), ('sms', 'SMS'), ('call', 'Call')], default='messenger', max_length=20)),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lead.lead')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='facebook.page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
