# Generated by Django 5.0.3 on 2024-04-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messenger_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
