# Generated by Django 5.0.3 on 2024-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_alter_lead_email_alter_lead_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('lead', 'Lead'), ('page', 'Page')], default='page', max_length=10),
        ),
    ]
