# Generated by Django 5.0.3 on 2024-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
