# Generated by Django 5.0.3 on 2024-04-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_last_message_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messenger_attachments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
