# Generated by Django 5.0.3 on 2024-04-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_message_messenger_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
