# Generated by Django 5.0.3 on 2024-04-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook_profile_pic',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
