# Generated by Django 5.0.3 on 2024-04-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_lead_facebook_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='facebook_profile_pic',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
