# Generated by Django 5.0.3 on 2024-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_alter_lead_facebook_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
