# Generated by Django 5.0.3 on 2024-04-14 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_messagestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagestatus',
            options={'verbose_name': 'Message Status', 'verbose_name_plural': 'Message Statuses'},
        ),
        migrations.AddField(
            model_name='lead',
            name='message_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.messagestatus'),
        ),
    ]
