# Generated by Django 5.0.3 on 2024-04-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_status_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='default', max_length=50)),
            ],
            options={
                'verbose_name': 'NextAction',
                'verbose_name_plural': 'NextActions',
            },
        ),
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.nextaction'),
        ),
    ]
