# Generated by Django 5.0.3 on 2024-04-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0017_nextaction_status_description_alter_lead_status_and_more'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nextaction',
            options={'verbose_name': 'Next Action', 'verbose_name_plural': 'Next Actions'},
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lead_message_statuses', to='system.company'),
        ),
        migrations.AddField(
            model_name='nextaction',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lead_next_actions', to='system.company'),
        ),
        migrations.AddField(
            model_name='status',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lead_statuses', to='system.company'),
        ),
    ]
