name: Django CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Environment Variables
      run: |
        echo "DJANGO_DEBUG=True" >> $GITHUB_ENV
        echo "DJANGO_SECRET_KEY=django-insecure-izb5+$$76l0kjrn6)i+$_5^mh6=j#u^(v2)+0hamstw$-(%!ha" >> $GITHUB_ENV
        echo "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0" >> $GITHUB_ENV
        echo "DJANGO_API_URL=http://localhost:8000/" >> $GITHUB_ENV
        echo "CSRF_TRUSTED_ORIGINS=http://localhost:8000" >> $GITHUB_ENV
        echo "CORS_ALLOWED_ORIGINS=http://localhost:8000" >> $GITHUB_ENV
        echo "S3_BUCKET_URL=''" >> $GITHUB_ENV
        echo "DJANGO_DB_ENGINE=django.db.backends.postgresql_psycopg2" >> $GITHUB_ENV
        echo "DJANGO_DB_NAME=django" >> $GITHUB_ENV
        echo "DJANGO_DB_USER=postgres" >> $GITHUB_ENV
        echo "DJANGO_DB_HOST=localhost" >> $GITHUB_ENV
        echo "DJANGO_DB_PASS=postgres" >> $GITHUB_ENV
        echo "DJANGO_DB_PORT=5432" >> $GITHUB_ENV

    - name: Setup Database
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run Tests
      run: |
        python manage.py test
